((nil . ((projectile-project-compilation-cmd . "cmake -B build -DLITESEQ_ENABLE_TESTING=ON -DLITESEQ_BUILD_EXAMPLE=ON -DCMAKE_BUILD_TYPE=Debug -S . && cmake --build build")
         (projectile-project-run-cmd . "./build/liteseq")
         (projectile-project-test-cmd . "ctest --verbose --test-dir build --output-on-failure")
         (eval . (setq cmake-ide-build-dir (expand-file-name "build" (projectile-project-root))))
         (eval . (setq cmake-ide-project-dir (projectile-project-root))))))
